// "Automatically correct spelling" (SPEC.md §29, typing). Google Docs asks its
// spelling service; Unitos keeps the everyday English typos it fixes on its
// own. A fix fires when a word ends; the typed word's first capital stays.

const FIXES: Record<string, string> = {
  i: "I",
  im: "I'm",
  ive: "I've",
  dont: "don't",
  doesnt: "doesn't",
  didnt: "didn't",
  cant: "can't",
  isnt: "isn't",
  arent: "aren't",
  wasnt: "wasn't",
  werent: "weren't",
  hasnt: "hasn't",
  havent: "haven't",
  hadnt: "hadn't",
  couldnt: "couldn't",
  shouldnt: "shouldn't",
  wouldnt: "wouldn't",
  youre: "you're",
  theyre: "they're",
  thats: "that's",
  theres: "there's",
  whats: "what's",
  teh: "the",
  hte: "the",
  adn: "and",
  nad: "and",
  taht: "that",
  thta: "that",
  waht: "what",
  wiht: "with",
  whit: "with",
  becuase: "because",
  beacuse: "because",
  becasue: "because",
  recieve: "receive",
  recieved: "received",
  beleive: "believe",
  belive: "believe",
  acheive: "achieve",
  seperate: "separate",
  definately: "definitely",
  definatly: "definitely",
  occured: "occurred",
  occurence: "occurrence",
  untill: "until",
  wich: "which",
  whcih: "which",
  thier: "their",
  freind: "friend",
  goverment: "government",
  enviroment: "environment",
  accomodate: "accommodate",
  adress: "address",
  begining: "beginning",
  calender: "calendar",
  comming: "coming",
  commited: "committed",
  completly: "completely",
  concious: "conscious",
  existance: "existence",
  foward: "forward",
  futher: "further",
  happend: "happened",
  independant: "independent",
  knowlege: "knowledge",
  neccessary: "necessary",
  necesary: "necessary",
  noticable: "noticeable",
  peice: "piece",
  posible: "possible",
  prefered: "preferred",
  probaly: "probably",
  realy: "really",
  reccomend: "recommend",
  recomend: "recommend",
  refered: "referred",
  relevent: "relevant",
  remeber: "remember",
  succesful: "successful",
  sucessful: "successful",
  suprise: "surprise",
  tommorow: "tomorrow",
  tomorow: "tomorrow",
  truely: "truly",
  wierd: "weird",
  writting: "writing",
  alot: "a lot",
  aswell: "as well",
  infact: "in fact",
};

/** The correction for a word just finished, or null. A one-letter word
    before "." is left alone: "i.e." stays. */
export function spellingFix(word: string, trigger: string): string | null {
  const key = word.toLowerCase().replace(/’/g, "'");
  const fix = FIXES[key];
  if (!fix || fix === word) return null;
  if (key.length === 1 && trigger === ".") return null;
  if (word[0] !== word[0].toLowerCase() && fix[0] === fix[0].toLowerCase()) {
    return fix[0].toUpperCase() + fix.slice(1);
  }
  return fix;
}
