import { languageName, profileLines, type PromptCtx } from "@/lib/prompts/types";

// VISUALIZE (SPEC.md §20, Unitos Ultra): the selection as a picture. The
// model places the passage in the whole article first — what it states, what
// it answers, extends, or replaces — and judges whether a picture can carry
// that core idea with certainty; only then does it draw — a diagram (a spec
// the server lays out), a simulation (a law the server integrates and draws
// in motion, lib/derive/simulate.ts), a picture (an SVG drawing), or an
// animation (an SVG with SMIL). It weighs the passage's own structure against the best analogy
// it can find, and takes whichever carries the idea; the reader's background
// says which analogies the reader already knows. A refusal is a valid output
// and the card shows its reason. Runs on VISUALIZE_MODEL (lib/derive/config.ts).
export function visualizePrompt(ctx: PromptCtx): string {
  const lang = languageName(ctx.lang);
  return [
    profileLines(ctx.profile),
    "",
    `The reader selected a passage from "${ctx.documentTitle}". The full document is above.`,
    "",
    "Context before the selection:",
    ctx.contextBefore || "(start of document)",
    "",
    "Selected passage:",
    ctx.anchoredText,
    "",
    "Context after the selection:",
    ctx.contextAfter || "(end of document)",
    "",
    "Task: turn the selected passage into one picture that delivers its core idea at a glance — or refuse.",
    "",
    "Step 1. Place the passage in the article, then find its core idea. Read the whole document above, not the passage alone. Say for yourself what the passage does there: it states a problem; it extends a problem stated earlier; it solves a problem stated earlier; it offers an alternative to a structure, a method, or an explanation given earlier; it is one step of a process the article builds up; it is an example of a claim made earlier; or it stands on its own. The core idea is the passage's point as it sits in the article, in one sentence — what the passage adds to what the article set up. When the passage answers, extends, or replaces something stated elsewhere, the picture shows both: the problem and this solution, the earlier structure and this alternative, the process and this step — because a reader who sees this passage's part alone does not see what it is for. Everything below serves that one idea; a picture that shows a side point of the passage is a wrong picture, not a partial one.",
    "",
    "Step 2. Find every way to draw it, then take the best one. There are three:",
    "- The equation in motion: when the passage is a law of change — an equation with a time derivative, or a description of how a state evolves under a rule — the picture is the state evolving under that law, the way a textbook animates the heat equation or a wave packet: the state at t = 0, the boundary, the law acting, over time. The server integrates the equation from your spec (the simulation kind below), so the motion is the equation's own, not a drawing of it. This is the picture for a PDE, an ODE, a rate law, a diffusion, a wave, a population, an oscillation. Never hand-draw the frames of such a thing as an animation: a drawn curve is a guess, an integrated one is the truth.",
    "- The literal picture: the passage's own structure — a sequence, a flow, a hierarchy, a cause and its effects, parts and how they fit, one quantity changing with another, a mechanism, a physical arrangement.",
    "- The analogy: a familiar thing that shares the idea's shape, drawn in place of it.",
    "Work out all three before you choose. A law of change takes the equation in motion. A passage whose own structure carries the idea takes the literal picture — an analogy there only adds a second thing to understand. A passage whose idea is abstract, unfamiliar, or has no drawable structure of its own is where the analogy earns its place: it is often the only picture that can carry such a passage, and reaching for one is the difference between a picture and a refusal. A formula that is not a law of change — a definition, an identity, a closed form — is drawn as what it does, never as its symbols: the shape it describes, the quantity it conserves, the state before and after.",
    "",
    "Step 3. When an analogy is in play, find the best one, not the first one. Name three candidates to yourself, then take the one that passes all five:",
    "1. Every part of the picture maps to a part of the passage, and you can say which to which.",
    "2. The analogy adds nothing the passage contradicts. What it implies beyond the passage is either true of the passage too or outside what the passage claims.",
    "3. The reader knows the analogue already, without being taught it. The reader context above says what they know — an analogy from their own field beats a general one.",
    "4. It breaks late. Every analogy breaks somewhere; the best one breaks outside what the passage says.",
    "5. It carries the idea better than the literal picture would.",
    "When no candidate passes all five, drop the analogy: use the literal picture, or refuse. An analogy the reader has to be taught first, or that carries a claim the passage does not make, is worse than no picture at all.",
    "",
    "Step 4. Decide whether to draw at all. Draw only when all four hold for the picture you chose:",
    "1. A picture shows this better than words do.",
    "2. You can draw it without inventing anything: every element and every relation is stated in the passage, in its context, or elsewhere in the document, or is the analogy's own and maps to something stated. What the article states elsewhere is there to be drawn — the problem this passage solves, the structure it replaces — and drawing it is not inventing.",
    "3. A reader who sees the picture without the passage takes away the passage's core idea, and not a different point.",
    "4. You are certain this picture is the best way to show it, not merely a possible way.",
    "When any one does not hold: set certain to false, set visual to null, and write in reason why a picture would not carry the passage's core idea — name what you tried, the literal picture and the analogies, so the reader knows the passage was worked on and not skipped. Do not draw a weak picture to have something to show. A refusal is the right output for a passage of opinion, of definitions, of narrative without structure, or of a claim whose whole content is in its words.",
    "",
    "Step 5. Pick the one kind that fits:",
    "- simulation: a law of change, integrated by the server and drawn as the state evolving over time — a loop of 8 seconds covering duration units of the law's time, with the state at t = 0 kept faint under the motion and a time bar. Give:",
    "  law: heat (∂u/∂t = α ∂²u/∂x²), wave (∂²u/∂t² = c² ∂²u/∂x²), advection (∂u/∂t + c ∂u/∂x = 0), schrodinger (iħ∂ψ/∂t = −(ħ²/2m)∂²ψ/∂x² + Vψ, ħ = 1, shown as |ψ|² with Re ψ faint and V dashed), or ode (a system dv/dt = f(t, v…), up to 4 variables, drawn as curves against time).",
    "  equation: the law as the passage writes it, at most 80 characters, shown above the plot.",
    "  x0, x1: the domain in x (a field law). initial: the state at t = 0 as a formula in x — for schrodinger the amplitude, with momentum k giving the phase e^{ikx}. velocity: for wave, ∂u/∂t at t = 0 (default 0). potential: for schrodinger, V(x) (default 0).",
    "  boundary: fixed (the ends hold their t = 0 values), insulated (no flux through the ends), periodic (the ends are one point). Take it from the passage: a rod with its ends in ice is fixed, a rod wrapped in insulation is insulated, a ring is periodic.",
    "  coefficient: α, c, or ħ/2m as the passage gives it; 1 when it does not.",
    "  variables: for ode, each with name, rate (a formula in t and every variable's name), and start.",
    "  duration: the time the picture covers, in the law's units — long enough that the law's point shows (the heat evens out, the wave reflects, the packet meets the barrier), not so long that nothing moves for most of the loop. Choose it from the coefficient and the domain: a diffusion needs about L²/α to even out, a wave about L/c to cross.",
    "  xLabel, uLabel: what x and u are in the passage's words — position along the rod, temperature.",
    "  Formulas: numbers, x (or t and the variable names), + − * / ^, parentheses, pi, e, and sin cos tan exp log sqrt abs tanh sinh cosh floor ceil round sign min max step(x) pulse(x, a, b), with comparisons giving 1 or 0. A Gaussian is exp(-(x-0.5)^2/0.01); a square pulse is pulse(x, 0.2, 0.4); a plucked string is sin(pi*x).",
    "- diagram: named things and the relations between them — a directed map. Give nodes and edges; the server lays them out. 3 to 12 nodes. A node label is at most 6 words; its detail, when it helps, at most 12 words. An edge label is at most 4 words. direction is right for a sequence or a flow, down for a hierarchy or a cause and its effects. Every node has a role: passage for what the passage itself states, article for what the article states elsewhere and the picture needs — the problem, the earlier structure, the step before. The server draws the passage's nodes strong and the article's nodes faint, so the reader sees at a glance what this passage adds. In an analogy the node label is the analogue's part and its detail is what that part stands for in the passage, so the mapping reads off the picture itself.",
    "- picture: a physical arrangement, a mechanism, a construction, or the shape a formula describes — one still drawing as SVG.",
    "- animation: a process whose steps happen over time and whose order is the point — a mechanism turning, a message passing, a cycle — as a loop of at most 8 seconds in SVG with SMIL (animate, animateTransform, animateMotion, set; repeatCount=\"indefinite\"). Every step of the loop is a step the passage states. Not for a law of change: that is a simulation.",
    "",
    "SVG rules for picture and animation:",
    "- viewBox=\"0 0 480 H\" with H between 280 and 480; no width or height attributes on the root; xmlns=\"http://www.w3.org/2000/svg\". The picture shows in a card 320 px wide, so draw for that size. Under 300000 characters, animation included.",
    "- Only these elements: svg, g, rect, circle, ellipse, line, polyline, polygon, path, text, tspan, title, desc, defs, marker, linearGradient, radialGradient, stop, clipPath, animate, animateTransform, animateMotion, mpath, set. No script, no foreignObject, no image, no style element, no reference outside the file, no event attribute. Anything else is removed.",
    "- First element: a white rect over the whole viewBox. Ink #2b2622. Accents: #b5563c, #5f7d5a, #b8912e, #6b5b95. Light fill #f3ede4. Write every color as one of these exact values: the stored picture re-tints itself for dark reading by matching them, and a color written any other way stays light on a dark page.",
    "- Legible at 320 px wide: stroke-width 2 to 3, text font-size 14 to 20, font-family=\"system-ui, sans-serif\", at most 36 characters per text line, 16 px margin from the edges, nothing overlapping.",
    "- Label every element the passage names. Labels use the passage's own words; what comes from elsewhere in the article uses the article's words.",
    "- When the picture shows the passage against what the article set up, the passage's own part is drawn in the accents and the rest in ink, so the reader sees at a glance what this passage adds.",
    "",
    "Step 6. Write the caption: one sentence, the picture's point, so the reader knows what they are looking at. When the picture shows the passage against what the article set up, the caption says the relation — the fix this passage gives to the problem above, the alternative it offers to the method before. When the picture is an analogy the caption says so and says what stands for what.",
    "",
    "Step 7. Check your own picture before you write it out. Read it as a reader who has not seen the passage: does it deliver the core idea from Step 1, does every part map to something stated, does any part overlap, run off the viewBox, or go unlabeled? Fix what fails. When it cannot be fixed, refuse instead — a refusal with a reason is a better answer than a picture that misleads.",
    "",
    `Write reason, caption, node labels, node details, edge labels, and SVG text in ${lang}.`,
    "",
    "Return ONLY this JSON, no other text:",
    "{",
    '  "judgment": {',
    '    "structure": "<one sentence: what the passage does in the article, its core idea, and the picture you chose for it — literal or the analogy, named — or none>",',
    '    "certain": true | false,',
    '    "reason": "<one or two sentences: why this picture is, or why no picture is, the best way to show this passage>"',
    "  },",
    '  "visual": null | {',
    '    "kind": "diagram" | "simulation" | "picture" | "animation",',
    '    "caption": "<one sentence>",',
    '    "diagram": { "direction": "right" | "down", "nodes": [{ "id": "n1", "label": "…", "detail": "…", "role": "passage" | "article" }], "edges": [{ "from": "n1", "to": "n2", "label": "…" }] },',
    '    "simulation": { "law": "heat" | "wave" | "advection" | "schrodinger" | "ode", "equation": "…", "x0": 0, "x1": 1, "initial": "…", "velocity": "…", "potential": "…", "momentum": 0, "boundary": "fixed" | "insulated" | "periodic", "coefficient": 1, "variables": [{ "name": "…", "rate": "…", "start": 0 }], "duration": 1, "xLabel": "…", "uLabel": "…" },',
    '    "svg": "<svg …>…</svg>"',
    "  }",
    "}",
    "diagram is present only for kind diagram; simulation only for kind simulation; svg only for kind picture or animation. visual is null whenever certain is false.",
  ].join("\n");
}
