/**
 * Probability lecture notes set as amsbook lecture notes are: a title page; a chapter with
 * numbered sections and run-in subsections; Definition, Exercise, Example, Proposition, Theorem, and Remark
 * blocks with small-caps heads and italic bodies; lettered items with hanging indents, items typed as lines
 * at the margin, nested items; inline and numbered display math (cases, aligned lines, sums, integrals,
 * a matrix); footnotes; citations; running heads that alternate the page number with the chapter's and the
 * section's names. The PDF has no ToUnicode maps, so math glyphs garble as in a pdfLaTeX file with no Unicode maps.
 */
import { b, chapter, eq, flushList, fn, h, i, li, li1, list, m, p, pi, role, row, runIn, table, theorem, title, up, type SpecBlock, type Spec, type TheoremStyle } from "../spec";

/** amsbook indents a theorem's head. */
const thm = (style: TheoremStyle, head: string, ...blocks: SpecBlock[]): SpecBlock => ({ ...theorem(style, head, ...blocks), indent: "first" });
const section = (...parts: Parameters<typeof b>) => h(2, b(...parts));
const sub = (text: string) => runIn(3, b(text));
/** A citation as amsbook prints it: the key in bold. */
const cite = (key: string, where?: string) => ["[", b(key), where ? `, ${where}]` : "]"];

const blocks: SpecBlock[] = [
  title(b("Probability and Measure")),
  role("subtitle", "Lecture notes for a first graduate course"),
  role("author", "Ada L. Mercer"),
  role("affiliation", "Department of Statistics, Northfield University"),
  role("date", "Fall 2026"),

  chapter(2, b("Random variables and expectation")),
  pi(
    "This chapter builds the objects that probability theory studies on top of the measure theory of Chapter 1. Section 2.1 introduces random variables as measurable functions and describes them through their laws and distribution functions. Section 2.2 defines the expectation as a Lebesgue integral, first for simple functions and then by monotone limits, and Section 2.3 collects the inequalities that control expectations and the spaces ",
    m("L^p"),
    " they lead to.",
  ),
  pi(
    "Throughout the chapter ",
    m("(\\Omega,\\mathcal{F},\\mathbf{P})"),
    " denotes a probability space, and we use the conventions ",
    m("\\inf\\emptyset=\\infty"),
    " and ",
    m("0\\cdot\\infty=0"),
    ". Unless we say otherwise, equalities and inequalities between random variables hold for every ",
    m("\\omega\\in\\Omega"),
    "; when they hold outside a set of probability zero we add the words “almost surely”, or a.s. for short.",
  ),

  section("2.1. Random variables and their distribution"),
  pi(
    "A random variable is a numerical quantity whose value is decided by the outcome of an experiment. To compute the probability that it falls in an interval, the set of outcomes that make it do so has to be an event. This single requirement is the whole definition.",
  ),
  sub("2.1.1. Measurable maps."),
  p("We state the requirement for maps between two measurable spaces, since the same notion covers random vectors, random sequences, and random functions."),
  thm(
    "plain",
    "Definition 2.1.1",
    p(
      "Let ",
      m("(S,\\mathcal{S})"),
      " and ",
      m("(T,\\mathcal{T})"),
      " be measurable spaces. A map ",
      m("f:S\\to T"),
      " is ",
      up("measurable"),
      " if ",
      m("f^{-1}(B)\\in\\mathcal{S}"),
      " for every ",
      m("B\\in\\mathcal{T}"),
      ". A ",
      up("random variable"),
      " is a measurable map ",
      m("X:(\\Omega,\\mathcal{F})\\to(\\mathbb{R},\\mathcal{B})"),
      ", where ",
      m("\\mathcal{B}"),
      " is the Borel ",
      m("\\sigma"),
      "-algebra of ",
      m("\\mathbb{R}"),
      ".",
      fn("1", "Some authors call any measurable map into a general space a random variable. We keep the name for real-valued maps and speak of random elements otherwise."),
    ),
  ),
  thm(
    "remark",
    "Remark",
    p(
      "Since the intervals ",
      m("(-\\infty,x]"),
      " generate ",
      m("\\mathcal{B}"),
      ", a function ",
      m("X:\\Omega\\to\\mathbb{R}"),
      " is a random variable as soon as ",
      m("\\{\\omega:X(\\omega)\\le x\\}\\in\\mathcal{F}"),
      " for every ",
      m("x\\in\\mathbb{R}"),
      ". Checking this one family of events is usually far easier than checking every Borel set.",
    ),
  ),
  thm(
    "plain",
    "Exercise 2.1.2",
    p("Let ", m("X,Y"), " be random variables on ", m("(\\Omega,\\mathcal{F})"), " and let ", m("c\\in\\mathbb{R}"), ". Show that the following are random variables."),
    list(
      li("(a)", up("Sums and products."), " ", m("X+Y"), ", ", m("cX"), " and ", m("XY"), "."),
      li("(b)", up("Maxima and minima."), " ", m("X\\vee Y=\\max(X,Y)"), " and ", m("X\\wedge Y=\\min(X,Y)"), ", and in particular the positive part ", m("X^+=X\\vee 0"), " and the negative part ", m("X^-=(-X)\\vee 0"), "."),
      li("(c)", up("Limits."), " For a sequence ", m("X_1,X_2,\\ldots"), " of random variables, the functions"),
      li1("(i)", m("\\sup_n X_n"), " and ", m("\\inf_n X_n"), ", when they are finite everywhere;"),
      li1("(ii)", m("\\limsup_{n\\to\\infty}X_n"), " and ", m("\\liminf_{n\\to\\infty}X_n"), ", under the same condition."),
      li("(d)", up("Compositions."), " ", m("g(X)"), " for every Borel function ", m("g:\\mathbb{R}\\to\\mathbb{R}"), ", that is, for every ", m("g"), " with ", m("g^{-1}(B)\\in\\mathcal{B}"), " for all ", m("B\\in\\mathcal{B}"), "."),
    ),
    p(up("Hint: "), "For (a) write ", m("\\{X+Y<x\\}"), " as a countable union, over the rationals ", m("q"), ", of the events ", m("\\{X<q\\}\\cap\\{Y<x-q\\}"), "."),
  ),
  thm(
    "plain",
    "Example 2.1.3",
    p(
      "The simplest random variables take finitely many values. For an event ",
      m("A\\in\\mathcal{F}"),
      " the ",
      up("indicator"),
      " ",
      m("I_A"),
      " equals ",
      m("1"),
      " on ",
      m("A"),
      " and ",
      m("0"),
      " off ",
      m("A"),
      ", and a ",
      up("simple function"),
      " is a finite combination",
    ),
    eq("X(\\omega)=\\sum_{k=1}^{n}c_k I_{A_k}(\\omega),\\qquad c_k\\in\\mathbb{R},\\ A_k\\in\\mathcal{F}.", "(2.1)"),
    p(
      "Every simple function is a random variable, since ",
      m("\\{X\\le x\\}"),
      " is a finite union of intersections of the sets ",
      m("A_k"),
      " and their complements. We may and shall assume that the sets ",
      m("A_k"),
      " are disjoint and the values ",
      m("c_k"),
      " distinct.",
    ),
  ),
  pi("Simple functions approximate every non-negative random variable from below, and this is how the expectation will be built in Section 2.2."),
  thm(
    "plain",
    "Proposition 2.1.4",
    p(
      "For every random variable ",
      m("X\\ge 0"),
      " there are simple functions ",
      m("0\\le X_1\\le X_2\\le\\cdots"),
      " with ",
      m("X_n(\\omega)\\uparrow X(\\omega)"),
      " for every ",
      m("\\omega\\in\\Omega"),
      ". One choice is",
    ),
    eq("X_n=\\sum_{k=1}^{n2^n}\\frac{k-1}{2^n}\\,I_{\\{(k-1)2^{-n}\\le X<k2^{-n}\\}}+n\\,I_{\\{X\\ge n\\}}.", "(2.2)"),
  ),
  thm(
    "proof",
    "Proof",
    p(
      "Each ",
      m("X_n"),
      " is simple, and ",
      m("X_n\\le X"),
      " by construction. Passing from ",
      m("n"),
      " to ",
      m("n+1"),
      " halves every dyadic interval, so ",
      m("X_n\\le X_{n+1}"),
      ". Finally, if ",
      m("X(\\omega)<n"),
      " then ",
      m("0\\le X(\\omega)-X_n(\\omega)<2^{-n}"),
      ", which gives the convergence.",
    ),
  ),

  sub("2.1.2. Laws and distribution functions."),
  p("A random variable carries the probability measure from ", m("\\Omega"), " to the real line, and most questions about one random variable concern only the measure it carries."),
  thm(
    "plain",
    "Definition 2.1.5",
    p(
      "The ",
      up("law"),
      " of a random variable ",
      m("X"),
      " is the probability measure ",
      m("\\mathcal{P}_X=\\mathbf{P}\\circ X^{-1}"),
      " on ",
      m("(\\mathbb{R},\\mathcal{B})"),
      ", that is, ",
      m("\\mathcal{P}_X(B)=\\mathbf{P}(X\\in B)"),
      ". Its ",
      up("distribution function"),
      " is ",
      m("F_X(x)=\\mathbf{P}(X\\le x)"),
      ". Two random variables with the same law are ",
      up("identically distributed"),
      ", and we write ",
      m("X\\overset{d}{=}Y"),
      ".",
    ),
  ),
  thm(
    "plain",
    "Theorem 2.1.6",
    p("A function ", m("F:\\mathbb{R}\\to[0,1]"), " is the distribution function of some random variable if and only if"),
    flushList(
      li("(a)", m("F"), " is non-decreasing,"),
      li("(b)", m("F"), " is right-continuous, that is, ", m("F(x+h)\\to F(x)"), " as ", m("h\\downarrow 0"), ","),
      li("(c)", m("\\lim_{x\\to-\\infty}F(x)=0"), " and ", m("\\lim_{x\\to\\infty}F(x)=1"), "."),
    ),
  ),
  pi(
    "Necessity follows from the continuity of probability measures along monotone sequences of events. For sufficiency one takes ",
    m("X(\\omega)=\\sup\\{y:F(y)<\\omega\\}"),
    " on the probability space ",
    m("((0,1),\\mathcal{B}_{(0,1)},U)"),
    ", where ",
    m("U"),
    " is the uniform measure; see ",
    ...cite("Dur19", "Theorem 1.2.2"),
    ".",
  ),
  thm(
    "plain",
    "Example 2.1.7",
    p("A coin that shows heads with probability ", m("p\\in(0,1)"), " gives the ", up("Bernoulli"), " random variable ", m("X=I_H"), ", whose distribution function is"),
    eq("F_X(x)=\\begin{cases}0, & x<0,\\\\ 1-p, & 0\\le x<1,\\\\ 1, & x\\ge 1.\\end{cases}", "(2.3)"),
    p("It jumps by ", m("1-p"), " at ", m("0"), " and by ", m("p"), " at ", m("1"), ", and it is constant elsewhere."),
  ),
  thm(
    "remark",
    "Remark",
    p(
      "A distribution function has at most countably many jumps, since fewer than ",
      m("k"),
      " of its jumps exceed ",
      m("1/k"),
      ". The law gives each jump point ",
      m("x"),
      " the mass ",
      m("F(x)-F(x^-)"),
      ", where ",
      m("F(x^-)=\\lim_{y\\uparrow x}F(y)"),
      ", and gives no mass to any other single point.",
    ),
  ),
  pi(
    "In statistics the law is unknown and is estimated from a sample. For independent observations ",
    m("X_1,\\ldots,X_n"),
    " with distribution function ",
    m("F"),
    ", the empirical distribution function ",
    m("\\widehat{F}_n(x)=\\frac{1}{n}\\sum_{i=1}^{n}I_{\\{X_i\\le x\\}}"),
    " estimates ",
    m("F"),
    ", and the sample mean ",
    m("\\bar{X}_n"),
    " estimates the mean; Section 2.4 makes independence precise.",
  ),
  thm(
    "plain",
    "Exercise 2.1.8",
    p(
      "Let ",
      m("X"),
      " have distribution function ",
      m("F"),
      ". Find the distribution functions of ",
      m("aX+b"),
      " for ",
      m("a>0"),
      ", of ",
      m("X^2"),
      ", and of ",
      m("e^{X}"),
      ", and express ",
      m("\\mathbf{P}(a<X<b)"),
      " and ",
      m("\\mathbf{P}(X=x)"),
      " in terms of ",
      m("F"),
      ".",
    ),
  ),

  section("2.2. Expectation"),
  pi(
    "The expectation of a random variable is its average value, weighted by probability. For a simple function the weights are explicit, and every other case is reduced to this one by approximation, following the construction of the Lebesgue integral.",
  ),
  sub("2.2.1. Simple functions."),
  p("Let ", m("X"), " be a simple function, written as in (2.1) with disjoint sets ", m("A_k"), "."),
  thm("plain", "Definition 2.2.1", p("The ", up("expectation"), " of the simple function ", m("X"), " in (2.1) is ", m("\\mathbf{E}X=\\sum_{k=1}^{n}c_k\\,\\mathbf{P}(A_k)"), ".")),
  pi(
    "The value does not depend on how ",
    m("X"),
    " is written, and two facts follow at once from the definition: for simple functions ",
    m("X"),
    " and ",
    m("Y"),
    " and real numbers ",
    m("a,b"),
    ",",
  ),
  eq("\\begin{aligned}\\mathbf{E}[aX+bY]&=a\\,\\mathbf{E}X+b\\,\\mathbf{E}Y,\\\\ X\\le Y&\\Longrightarrow\\mathbf{E}X\\le\\mathbf{E}Y.\\end{aligned}", "(2.4)"),
  p("The first is ", i("linearity"), " and the second ", i("monotonicity"), "; both carry over to every integrable random variable."),
  sub("2.2.2. Monotone limits."),
  p("For a random variable ", m("X\\ge 0"), " we approximate ", m("X"), " from below by simple functions and define"),
  eq("\\mathbf{E}X=\\sup\\{\\mathbf{E}Y:\\ Y\\text{ simple},\\ 0\\le Y\\le X\\}\\in[0,\\infty].", "(2.5)"),
  p(
    "For a general ",
    m("X"),
    " we set ",
    m("\\mathbf{E}X=\\mathbf{E}X^+-\\mathbf{E}X^-"),
    " whenever at least one of the two terms is finite, and we call ",
    m("X"),
    " ",
    i("integrable"),
    " when both are, that is, when ",
    m("\\mathbf{E}|X|<\\infty"),
    ".",
  ),
  thm("plain", "Theorem 2.2.2", p(up("(Monotone convergence)"), " If ", m("0\\le X_n\\uparrow X"), " then ", m("\\mathbf{E}X_n\\uparrow\\mathbf{E}X"), ".")),
  thm(
    "plain",
    "Exercise 2.2.3",
    p("Use Theorem 2.2.2 and the simple functions of Proposition 2.1.4 to prove the following."),
    list(
      li("(a)", "Linearity and monotonicity (2.4) hold for all integrable ", m("X"), " and ", m("Y"), "."),
      li("(b)", up("Fatou’s lemma."), " If ", m("X_n\\ge 0"), " then ", m("\\mathbf{E}[\\liminf_n X_n]\\le\\liminf_n\\mathbf{E}X_n"), "."),
      li("(c)", up("Dominated convergence."), " If ", m("X_n\\to X"), " and ", m("|X_n|\\le Y"), " for an integrable ", m("Y"), ", then ", m("\\mathbf{E}X_n\\to\\mathbf{E}X"), " and in fact ", m("\\mathbf{E}|X_n-X|\\to 0"), "."),
      li("(d)", "If ", m("X_n\\ge 0"), " then ", m("\\mathbf{E}\\sum_{n=1}^{\\infty}X_n=\\sum_{n=1}^{\\infty}\\mathbf{E}X_n"), ", whether or not the sums are finite."),
    ),
  ),
  thm(
    "plain",
    "Example 2.2.4",
    p(
      "A random variable ",
      m("N"),
      " with ",
      m("\\mathbf{P}(N=k)=e^{-\\lambda}\\lambda^k/k!"),
      " for ",
      m("k=0,1,2,\\ldots"),
      " has the ",
      up("Poisson"),
      " law with parameter ",
      m("\\lambda>0"),
      ". By Exercise 2.2.3(d),",
    ),
    eq("\\mathbf{E}N=\\sum_{k=0}^{\\infty}k\\,\\frac{e^{-\\lambda}\\lambda^k}{k!}=\\lambda e^{-\\lambda}\\sum_{k=1}^{\\infty}\\frac{\\lambda^{k-1}}{(k-1)!}=\\lambda.", "(2.6)"),
    p("The same computation with ", m("k(k-1)"), " in place of ", m("k"), " gives ", m("\\mathbf{E}[N(N-1)]=\\lambda^2"), "."),
  ),
  pi(
    "The expectation of a function of ",
    m("X"),
    " depends only on the law of ",
    m("X"),
    ". This is the ",
    i("change of variables formula"),
    ":",
    fn("2", "It is the probabilistic form of the substitution rule of calculus; see ", ...cite("Wil91", "Section 6.12"), "."),
  ),
  eq("\\mathbf{E}\\,g(X)=\\int_{\\mathbb{R}}g(x)\\,d\\mathcal{P}_X(x)=\\int_{-\\infty}^{\\infty}g(x)f_X(x)\\,dx,", "(2.7)"),
  p("where the second equality holds when the law of ", m("X"), " has a density ", m("f_X"), ", that is, when ", m("F_X(x)=\\int_{-\\infty}^{x}f_X(y)\\,dy"), " for every ", m("x"), "."),
  thm(
    "remark",
    "Remark",
    p("For a random vector ", m("\\mathbf{X}=(X_1,X_2)"), " with ", m("\\mathbf{E}X_i^2<\\infty"), " the same formula gives the ", i("covariance matrix")),
    eq("\\Sigma=\\begin{pmatrix}\\operatorname{Var}X_1 & \\operatorname{Cov}(X_1,X_2)\\\\ \\operatorname{Cov}(X_2,X_1) & \\operatorname{Var}X_2\\end{pmatrix},\\qquad\\operatorname{Cov}(X,Y)=\\mathbf{E}[(X-\\mathbf{E}X)(Y-\\mathbf{E}Y)],"),
    p("which is symmetric and non-negative definite, since ", m("a^{\\top}\\Sigma a=\\operatorname{Var}(a_1X_1+a_2X_2)\\ge 0"), " for every ", m("a\\in\\mathbb{R}^2"), "."),
  ),

  section("2.3. Inequalities and ", m("L^p"), " spaces"),
  pi("Many limit theorems reduce to bounds on tail probabilities and on moments. This section collects the inequalities used most often."),
  sub("2.3.1. Markov and Chebyshev."),
  p("The first bound needs nothing but monotonicity."),
  thm("plain", "Proposition 2.3.1", p(up("(Markov’s inequality)"), " For a random variable ", m("X"), " and ", m("a>0"), ", ", m("\\mathbf{P}(|X|\\ge a)\\le\\mathbf{E}|X|/a"), ".")),
  thm("proof", "Proof", p("Since ", m("a\\,I_{\\{|X|\\ge a\\}}\\le|X|"), ", monotonicity gives ", m("a\\,\\mathbf{P}(|X|\\ge a)\\le\\mathbf{E}|X|"), ".")),
  pi(
    "Applied to ",
    m("(X-\\mathbf{E}X)^2"),
    " it gives ",
    i("Chebyshev’s inequality"),
    " ",
    m("\\mathbf{P}(|X-\\mathbf{E}X|\\ge a)\\le\\operatorname{Var}(X)/a^2"),
    ", and applied to ",
    m("e^{tX}"),
    " it gives the exponential bound ",
    m("\\mathbf{P}(X\\ge a)\\le e^{-ta}\\,\\mathbf{E}e^{tX}"),
    " for every ",
    m("t>0"),
    ".",
  ),
  thm(
    "plain",
    "Exercise 2.3.2",
    p(
      "Let ",
      m("X_1,\\ldots,X_n"),
      " be random variables with ",
      m("\\mathbf{E}X_i=0"),
      " and ",
      m("\\mathbf{E}X_i^2=\\sigma^2"),
      ", uncorrelated in pairs, and let ",
      m("S_n=X_1+\\cdots+X_n"),
      ".",
    ),
    list(
      li("(a)", "Show that ", m("\\operatorname{Var}(S_n)=n\\sigma^2"), "."),
      li("(b)", "Deduce the weak law of large numbers: ", m("\\mathbf{P}(|S_n/n|\\ge\\epsilon)\\le\\sigma^2/(n\\epsilon^2)\\to 0"), " for every ", m("\\epsilon>0"), "."),
      li("(c)", "Suppose in addition that the ", m("X_i"), " are independent, symmetric, and bounded by ", m("1"), ". Using the exponential bound with a well chosen ", m("t"), ", show that"),
      li1("(i)", m("\\mathbf{E}e^{tX_i}\\le\\cosh t\\le e^{t^2/2}"), " for every ", m("t>0"), ", and"),
      li1("(ii)", m("\\mathbf{P}(S_n\\ge a)\\le e^{-a^2/(2n)}"), " for every ", m("a>0"), "."),
    ),
  ),
  sub("2.3.2. Jensen, Hölder and Minkowski."),
  p(
    "A function ",
    m("\\varphi:\\mathbb{R}\\to\\mathbb{R}"),
    " is ",
    i("convex"),
    " if ",
    m("\\varphi(\\theta x+(1-\\theta)y)\\le\\theta\\varphi(x)+(1-\\theta)\\varphi(y)"),
    " for all ",
    m("x,y"),
    " and ",
    m("\\theta\\in[0,1]"),
    ".",
  ),
  thm(
    "plain",
    "Theorem 2.3.3",
    p(up("(Jensen’s inequality)"), " If ", m("\\varphi"), " is convex and both ", m("X"), " and ", m("\\varphi(X)"), " are integrable, then"),
    eq("\\varphi(\\mathbf{E}X)\\le\\mathbf{E}\\varphi(X).", "(2.8)"),
  ),
  thm(
    "plain",
    "Definition 2.3.4",
    p(
      "For ",
      m("p\\in[1,\\infty)"),
      " let ",
      m("\\|X\\|_p=(\\mathbf{E}|X|^p)^{1/p}"),
      ", and let ",
      m("L^p"),
      " denote the space of random variables with ",
      m("\\|X\\|_p<\\infty"),
      ", two of them identified when they are equal a.s. We also set ",
      m("\\|X\\|_\\infty=\\inf\\{c:\\mathbf{P}(|X|>c)=0\\}"),
      ".",
    ),
  ),
  pi("With these norms the classical inequalities of analysis read as follows. Their proofs are the same as for finite sums, and we leave them to the reader (see ", ...cite("Bil95", "Section 5"), " for details)."),
  eq("\\mathbf{E}|XY|\\le\\|X\\|_p\\|Y\\|_q\\quad\\text{for }\\tfrac{1}{p}+\\tfrac{1}{q}=1,\\qquad\\|X+Y\\|_p\\le\\|X\\|_p+\\|Y\\|_p.", "(2.9)"),
  p(
    "The first is ",
    i("Hölder’s inequality"),
    " and the second ",
    i("Minkowski’s inequality"),
    ". Taking ",
    m("Y=1"),
    " in the first shows that ",
    m("\\|X\\|_p"),
    " is non-decreasing in ",
    m("p"),
    ", so that ",
    m("L^q\\subseteq L^p"),
    " whenever ",
    m("p\\le q"),
    ".",
  ),
  thm(
    "plain",
    "Exercise 2.3.5",
    p("Let ", m("X\\ge 0"), " be a random variable."),
    list(
      li("(a)", "Show that ", m("\\mathbf{E}X=\\int_0^\\infty\\mathbf{P}(X>t)\\,dt"), ". More generally, show that for every ", m("p>0"), " the moment ", m("\\mathbf{E}X^p"), " equals ", m("\\int_0^\\infty p\\,t^{p-1}\\mathbf{P}(X>t)\\,dt"), "."),
      li("(b)", "Deduce that ", m("\\mathbf{E}X<\\infty"), " if and only if ", m("\\sum_{n\\ge 1}\\mathbf{P}(X\\ge n)<\\infty"), "."),
      li("(c)", "Show that if ", m("\\|X\\|_\\infty<\\infty"), " then ", m("\\|X\\|_p\\to\\|X\\|_\\infty"), " as ", m("p\\to\\infty"), ", and that the limit is ", m("\\infty"), " otherwise."),
    ),
    p(up("Hint: "), "For (a) write ", m("X=\\int_0^\\infty I_{\\{X>t\\}}\\,dt"), " and interchange the expectation and the integral."),
  ),
  thm(
    "remark",
    "Remark",
    p(
      "The space ",
      m("L^2"),
      " is special: ",
      m("\\langle X,Y\\rangle=\\mathbf{E}XY"),
      " is an inner product on it, and ",
      m("L^2"),
      " is a Hilbert space. Orthogonal projection onto a closed subspace of ",
      m("L^2"),
      " is the starting point for conditional expectation in Chapter 4, following ",
      ...cite("Wil91", "Chapter 9"),
      ".",
    ),
  ),

  section("2.4. Independence"),
  pi(
    "Independence is what separates probability theory from the rest of measure theory. It lets us compute the law of a sum from the laws of its terms, and it is the assumption behind every limit theorem in the chapters that follow. We define it first for events and ",
    m("\\sigma"),
    "-algebras, and then for random variables.",
  ),
  thm(
    "plain",
    "Definition 2.4.1",
    p("Events ", m("A_1,\\ldots,A_n\\in\\mathcal{F}"), " are ", up("independent"), " if"),
    eq("\\mathbf{P}\\Bigl(\\bigcap_{i\\in I}A_i\\Bigr)=\\prod_{i\\in I}\\mathbf{P}(A_i)\\qquad\\text{for every }I\\subseteq\\{1,\\ldots,n\\}.", "(2.10)"),
    p(
      "Sub-",
      m("\\sigma"),
      "-algebras ",
      m("\\mathcal{G}_1,\\ldots,\\mathcal{G}_n"),
      " of ",
      m("\\mathcal{F}"),
      " are independent if (2.10) holds whenever ",
      m("A_i\\in\\mathcal{G}_i"),
      " for each ",
      m("i"),
      ", and random variables are independent when the ",
      m("\\sigma"),
      "-algebras ",
      m("\\sigma(X_i)=\\{X_i^{-1}(B):B\\in\\mathcal{B}\\}"),
      " they generate are.",
    ),
  ),
  pi(
    "Pairwise independence does not imply independence. Toss two fair coins and let ",
    m("A"),
    " be the event that the first shows heads, ",
    m("B"),
    " that the second shows heads, and ",
    m("C"),
    " that the two coins agree. Any two of these events are independent, each having probability ",
    m("\\tfrac12"),
    " and each pair meeting with probability ",
    m("\\tfrac14"),
    ", but ",
    m("\\mathbf{P}(A\\cap B\\cap C)=\\tfrac14\\neq\\tfrac18"),
    ". Checking (2.10) for every subset ",
    m("I"),
    ", and not only for pairs, is therefore essential, although for ",
    m("\\sigma"),
    "-algebras generated by ",
    m("\\pi"),
    "-systems it is enough to check the generators.",
    fn("3", "This is a consequence of Dynkin’s ", m("\\pi"), "-", m("\\lambda"), " theorem; see ", ...cite("Bil95", "Theorem 3.2"), "."),
  ),
  thm(
    "plain",
    "Example 2.4.2",
    p("Roll two fair dice and let ", m("S"), " be the sum of the faces. The law of ", m("S"), " is given by the following table."),
  ),
  table(
    { layout: { rules: "grid", align: "lccccccccccc", small: true } },
    row(m("k"), m("2"), m("3"), m("4"), m("5"), m("6"), m("7"), m("8"), m("9"), m("10"), m("11"), m("12")),
    row(
      m("\\mathbf{P}(S=k)"),
      m("\\frac{1}{36}"),
      m("\\frac{2}{36}"),
      m("\\frac{3}{36}"),
      m("\\frac{4}{36}"),
      m("\\frac{5}{36}"),
      m("\\frac{6}{36}"),
      m("\\frac{5}{36}"),
      m("\\frac{4}{36}"),
      m("\\frac{3}{36}"),
      m("\\frac{2}{36}"),
      m("\\frac{1}{36}"),
    ),
  ),
  pi("Each entry counts the pairs of faces with the given sum and divides by the 36 equally likely pairs; the independence of the two dice is what makes the pairs equally likely."),
  thm(
    "plain",
    "Proposition 2.4.3",
    p("If ", m("X"), " and ", m("Y"), " are independent and integrable, then ", m("XY"), " is integrable and ", m("\\mathbf{E}[XY]=\\mathbf{E}X\\,\\mathbf{E}Y"), "."),
  ),
  thm(
    "proof",
    "Proof",
    p(
      "For indicators ",
      m("X=I_A"),
      " and ",
      m("Y=I_B"),
      " the identity is ",
      m("\\mathbf{P}(A\\cap B)=\\mathbf{P}(A)\\mathbf{P}(B)"),
      ". Linearity extends it to simple functions, monotone convergence to non-negative random variables, and the decomposition ",
      m("X=X^+-X^-"),
      " to the integrable case.",
    ),
  ),
  thm(
    "plain",
    "Exercise 2.4.4",
    p("Let ", m("X_1,X_2,\\ldots"), " be independent random variables with the same law, and let ", m("M_n=\\max(X_1,\\ldots,X_n)"), "."),
    list(
      li("(a)", "Show that ", m("\\mathbf{P}(M_n\\le x)=F(x)^n"), ", where ", m("F"), " is the common distribution function."),
      li("(b)", "When the law is exponential with parameter ", m("1"), ", so that ", m("F(x)=1-e^{-x}"), " for ", m("x\\ge 0"), ", show that"),
      li1("(i)", m("\\mathbf{P}(M_n-\\log n\\le x)\\to\\exp(-e^{-x})"), " for every real ", m("x"), ";"),
      li1("(ii)", m("M_n/\\log n\\to 1"), " in probability;"),
      li1("(iii)", m("\\mathbf{E}M_n=\\sum_{k=1}^{n}1/k"), ", so that ", m("\\mathbf{E}M_n-\\log n"), " converges."),
      li("(c)", "Explain why independence is needed in part (a) but not in the definition of ", m("M_n"), "."),
    ),
  ),
  pi("The next result is the main tool for showing that an event happens only finitely often. Its first half needs no independence at all, which makes it one of the most used facts in the subject."),
  thm(
    "plain",
    "Theorem 2.4.5",
    p(up("(Borel–Cantelli lemmas)"), " Let ", m("A_1,A_2,\\ldots"), " be events. The event that infinitely many of them occur is ", m("\\limsup_n A_n=\\bigcap_{m\\ge 1}\\bigcup_{n\\ge m}A_n"), "."),
    list(
      li("(a)", "If ", m("\\sum_{n}\\mathbf{P}(A_n)<\\infty"), " then ", m("\\mathbf{P}(\\limsup_n A_n)=0"), "."),
      li("(b)", "If the events are independent and ", m("\\sum_{n}\\mathbf{P}(A_n)=\\infty"), " then ", m("\\mathbf{P}(\\limsup_n A_n)=1"), "."),
    ),
  ),
  thm(
    "proof",
    "Proof",
    p("For (a), let ", m("N=\\sum_n I_{A_n}"), " count the events that occur. By Exercise 2.2.3(d), ", m("\\mathbf{E}N=\\sum_n\\mathbf{P}(A_n)<\\infty"), ", so ", m("N<\\infty"), " a.s. For (b), independence and the bound ", m("1-x\\le e^{-x}"), " give"),
    eq("\\mathbf{P}\\Bigl(\\bigcap_{n=m}^{M}A_n^c\\Bigr)=\\prod_{n=m}^{M}\\bigl(1-\\mathbf{P}(A_n)\\bigr)\\le\\exp\\Bigl(-\\sum_{n=m}^{M}\\mathbf{P}(A_n)\\Bigr)\\longrightarrow 0", "(2.11)"),
    p("as ", m("M\\to\\infty"), ", for every ", m("m"), ". Hence ", m("\\mathbf{P}(\\bigcup_{n\\ge m}A_n)=1"), " for every ", m("m"), ", and the intersection over ", m("m"), " has probability one as well."),
  ),
  pi(
    "As an application, let ",
    m("X_1,X_2,\\ldots"),
    " be independent with the exponential law of Exercise 2.4.4. Since ",
    m("\\mathbf{P}(X_n>c\\log n)=n^{-c}"),
    ", the series ",
    m("\\sum_n n^{-c}"),
    " converges exactly when ",
    m("c>1"),
    ", and the two lemmas together show that ",
    m("\\limsup_n X_n/\\log n=1"),
    " almost surely. Results of this kind, which pin down the size of the largest fluctuations of a sequence, are the subject of the law of the iterated logarithm; see ",
    ...cite("Dur19", "Section 8.5"),
    ".",
  ),

  section("Bibliography"),
  list(
    li("[Bil95]", "P. Billingsley, ", i("Probability and measure"), ", third ed., John Wiley & Sons, New York, 1995."),
    li("[Dur19]", "R. Durrett, ", i("Probability: theory and examples"), ", fifth ed., Cambridge University Press, Cambridge, 2019."),
    li("[Wil91]", "D. Williams, ", i("Probability with martingales"), ", Cambridge University Press, Cambridge, 1991."),
  ),
];

export const notes: Spec = {
  name: "notes",
  title: "Probability and Measure: lecture notes",
  category: "math-tex",
  blocks,
  renderings: {
    tex: {
      documentClass: "amsbook",
      classOptions: "openany",
      noToUnicode: true,
      preamble: "",
      headings: {
        2: { command: "section", bold: true, mark: "markright" },
        3: { command: "subsection", bold: true },
      },
      front: "plain",
      smallCaps: "keep",
      bands: { top: 106, bottom: 85 },
      // amsbook's sizes in Computer Modern as pdflatex prints them.
      fonts: {
        body: { shape: "serif", size: 9.96 },
        title: { shape: "serif", size: 14.35, bold: true },
        subtitle: { shape: "serif", size: 11.96 },
        author: { shape: "serif", size: 10.91 },
        h1: { shape: "serif", size: 14.35, bold: true },
        h2: { shape: "serif", size: 9.96, bold: true },
        h3: { shape: "serif", size: 9.96, bold: true },
        footnote: { shape: "serif", size: 7.97 },
      },
      centered: [1, 2],
      justified: true,
    },
    // The same notes printed from HTML: Latin Modern text with real small caps, KaTeX math, and running heads
    // that alternate the page number and the book's title with the chapter's.
    html: {
      css: `
@page { size: letter; margin: 1.35in 1.5in 1.2in; }
@page :first { @top-left { content: none; } @top-center { content: none; } @top-right { content: none; } }
@page :left { @top-left { content: counter(page); font: 8pt "Latin Modern Roman"; vertical-align: bottom; padding-bottom: 14pt; } @top-center { content: "2. RANDOM VARIABLES AND EXPECTATION"; font: 8pt "Latin Modern Roman"; vertical-align: bottom; padding-bottom: 14pt; } }
@page :right { @top-center { content: "PROBABILITY AND MEASURE"; font: 8pt "Latin Modern Roman"; vertical-align: bottom; padding-bottom: 14pt; } @top-right { content: counter(page); font: 8pt "Latin Modern Roman"; vertical-align: bottom; padding-bottom: 14pt; } }
body { font: 10.5pt/1.38 "Latin Modern Roman", serif; text-align: justify; hyphens: auto; }
p { margin: 0; }
p.title { font-size: 20pt; font-weight: bold; text-align: center; margin: 2.2in 0 0.3in; }
.role { margin-bottom: 0.18in; }
p.role-subtitle { font-size: 14pt; }
p.role-date { break-after: page; }
p.chapter-label { font-size: 10.5pt; margin-top: 1.1in; }
h1.chapter { font-size: 15pt; text-align: center; margin: 0.3in 0 0.35in; }
h2 { font-size: 10.5pt; text-align: center; margin: 1.1em 0 0.5em; }
.run-in { font-weight: bold; }
.thm { margin: 0.55em 0; }
.list { margin: 0.2em 0; }
.item > .marker { min-width: 2.2em; }
.display { margin: 0.4em 0; }
.table-wrap { margin: 0.6em 0; }
table.grid td { padding: 1pt 5pt; }
p.footnote { font-size: 8.5pt; margin-top: 0.4em; }
.qed { font-family: "DejaVu Sans"; }
.katex { font-size: 1.05em; }
`,
      bands: { top: 90, bottom: 60 },
    },
  },
  notes:
    "The chapter's “CHAPTER 2” line is its own centered paragraph above the level 1 heading. A run-in heading is a heading block; the rest of its line is the next paragraph. A proof ends with the box □. In LaTeX a footnote block stands after the block with its mark (the mark is part of that block's text); in HTML the footnotes stand at the end.",
};

